### ISSUE TITLE
zip files

### ISSUE THREAD

**Issue by ppasedach** [wujastyk/GRETIL-mirror#1]
The zip files should probably be removed from the git tracking, because, I suppose, they will be regenerated with every update to GRETIL, and although when unzipped just containing few differences, as binary files they will differ almost completely, and quickly increase the size of the repository to enormous proportions.

**Comment by wujastyk** [comment]
Good advice.  I was already thinking I should do that.  I'll do it now.

**Comment by wujastyk** [comment]
Done.
